### ISSUE TITLE
bibtex format different between ES and DB

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1062]
The bibtex responses are different for ES and DB. This happens despite reindexing, so something funny is going on.
```
 curl -H 'Accept: application/x-bibtex'
 "https://inspirehep.net/api/literature/812045"

```
 VS
```
 curl --get --data-urlencode 'q=eprint arXiv:0901.4744' -H 'accept:
 application/x-bibtex' --silent "https://inspirehep.net/api/literature"
```

```
curl --user-agent "checkbib:gamboz@medialab.sissa.it" -H 'Accept:
 application/x-bibtex' "https://inspirehep.net/api/literature/812046"
``` 
VS
```
 curl --get --data-urlencode 'q=eprint arXiv:0901.4748' -H 'accept:
 application/x-bibtex' --silent "https://inspirehep.net/api/literature"
 ``

**Comment by michamos** [comment]
More cases:
```
curl -H "Accept: application/x-bibtex"
"https://inspirehep.net/api/literature/779971"
@article{Sakellariadou:2008ie,
    author = "Sakellariadou, Mairi",
    title = "{Cosmic Superstrings}",
    eprint = "0802.3379",
    archivePrefix = "arXiv",
    primaryClass = "hep-th",
    doi = "10.1098/rsta.2008.0068",
    journal = "Phil. Trans. Roy. Soc. Lond. A",
    volume = "366",
    pages = "2881--2894",
    year = "2008"
}


curl -H "Accept: application/x-bibtex" --get --data-urlencode "q=find
doi 10.1098/rsta.2008.0068"  "https://inspirehep.net/api/literature"
@article{Sakellariadou:2008ie,
    author = "Sakellariadou, Mairi",
    title = "{Cosmic Superstrings}",
    eprint = "0802.3379",
    archivePrefix = "arXiv",
    primaryClass = "hep-th",
    doi = "10.1098/rsta.2008.0068",
    month = "2",
    year = "2008"
}
``

**Comment by monaawi** [comment]
All the cases were fixed after reindexing so it is most probably an indexing issue

**Comment by michamos** [comment]
@monaawi did you reindex them manually or did you do a bulk reindexing? I have noticed that manually reindexing them seems to work, but they were still wrong after remigration + bulk reindexing.

**Comment by michamos** [comment]
More examples:
```
curl --get --data-urlencode 'q=eprint arXiv:0803.2475' -H 'accept:
application/x-bibtex' --silent "https://inspirehep.net/api/literature"
@article{Dixon:2008tu,
    author = "Dixon, Lance J.",
    editor = "Catani, Stefano and Colferai, Dimitri and Grazzini,
Massimiliano",
    title = "{Gluon scattering in N=4 super-Yang-Mills theory from weak
to strong coupling}",
    eprint = "0803.2475",
    archivePrefix = "arXiv",
    primaryClass = "hep-th",
    reportNumber = "SLAC-PUB-13167",
    year = "2007"
}


curl  -H 'accept: application/x-bibtex' --silent
"https://inspirehep.net/api/literature/781511"
@article{Dixon:2008tu,
    author = "Dixon, Lance J.",
    editor = "Catani, Stefano and Colferai, Dimitri and Grazzini,
Massimiliano",
    title = "{Gluon scattering in N=4 super-Yang-Mills theory from weak
to strong coupling}",
    eprint = "0803.2475",
    archivePrefix = "arXiv",
    primaryClass = "hep-th",
    reportNumber = "SLAC-PUB-13167",
    journal = "PoS",
    volume = "RADCOR2007",
    pages = "056",
    year = "2007"
}
```

```
curl --get --data-urlencode 'q=find J "Pramana,72,69"' -H 'accept:
application/x-bibtex' --silent "https://inspirehep.net/api/literature"
@article{Magnea:2008ga,
    author = "Magnea, Lorenzo",
    editor = "Basu, Rahul",
    title = "{All-order results for soft and collinear gluons}",
    eprint = "0806.3353",
    archivePrefix = "arXiv",
    primaryClass = "hep-ph",
    reportNumber = "DFTT-16-2008",
    doi = "10.1007/s12043-009-0006-y",
    month = "6",
    year = "2008"
}

curl -H 'accept: application/x-bibtex' --silent
"https://inspirehep.net/api/literature/788797"
@article{Magnea:2008ga,
    author = "Magnea, Lorenzo",
    editor = "Basu, Rahul",
    title = "{All-order results for soft and collinear gluons}",
    eprint = "0806.3353",
    archivePrefix = "arXiv",
    primaryClass = "hep-ph",
    reportNumber = "DFTT-16-2008",
    doi = "10.1007/s12043-009-0006-y",
    journal = "Pramana",
    volume = "72",
    pages = "69--81",
    year = "2009"
}
```
```
curl --get --data-urlencode 'q=eprint arXiv:1006.1536' -H 'accept:
application/x-bibtex' --silent "https://inspirehep.net/api/literature"
@article{Koerber:2010bx,
    author = "Koerber, Paul",
    title = "{Lectures on Generalized Complex Geometry for Physicists}",
    eprint = "1006.1536",
    archivePrefix = "arXiv",
    primaryClass = "hep-th",
    reportNumber = "KUL-TF-10-04",
    doi = "10.1002/prop.201000083",
    month = "6",
    year = "2010"
}


curl -H 'accept: application/x-bibtex' --silent
"https://inspirehep.net/api/literature/857596"
@article{Koerber:2010bx,
    author = "Koerber, Paul",
    title = "{Lectures on Generalized Complex Geometry for Physicists}",
    eprint = "1006.1536",
    archivePrefix = "arXiv",
    primaryClass = "hep-th",
    reportNumber = "KUL-TF-10-04",
    doi = "10.1002/prop.201000083",
    journal = "Fortsch. Phys.",
    volume = "59",
    pages = "169--242",
    year = "2011"
}
```
```
curl --get --data-urlencode 'q=find J "Subnucl.Ser.,15,943"' -H 'accept:
application/x-bibtex' --silent "https://inspirehep.net/api/literature"
@article{tHooft:1977xjm,
    author = "'t Hooft, Gerard",
    editor = "Zichichi, Antonino",
    title = "{Can We Make Sense Out of Quantum Chromodynamics?}",
    reportNumber = "PRINT-77-0723 (UTRECHT)",
    month = "8",
    year = "1977"
}

curl -H 'accept: application/x-bibtex' --silent
"https://inspirehep.net/api/literature/5753"
@article{tHooft:1977xjm,
    author = "'t Hooft, Gerard",
    editor = "Zichichi, Antonino",
    title = "{Can We Make Sense Out of Quantum Chromodynamics?}",
    reportNumber = "PRINT-77-0723 (UTRECHT)",
    journal = "Subnucl. Ser.",
    volume = "15",
    pages = "943",
    year = "1979"
}
```

**Comment by michamos** [comment]
To reiterate once more: this is not due to a failure of reindexing stuff on record update, as most of these records are old and have not been updated recently. This seems to be a difference of behavior between indexing a single record and bulk reindexing (after migration?)
